server.port=16000
spring.application.name=weather-tool

spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

hefeng.api.key=29d8323b19e5487e883441a934a20e20
hefeng.api.host=https://devapi.qweather.com/v7

spring.cache.cache-names=weather,city
